In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn.metrics import classification_report, confusion_matrix  
from sklearn.naive_bayes import GaussianNB
from imblearn.over_sampling import SMOTE
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestRegressor

C:\Users\ISHAAN\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [3]:
trainText = pd.read_csv('text_train_5_df.txt')
trainAudio = pd.read_csv('audio_train_df.txt')
trainVideo = pd.read_csv('visual_train_df.txt')
trainAudio.bully[trainAudio.bully == 'bullying'] = 1
trainAudio.bully[trainAudio.bully == 'noneBll'] = 0
# trainVideo.bully[trainVideo.bully == 'bullying'] = 1
# trainVideo.bully[trainVideo.bully == 'noneBll'] = 0


C:\Users\ISHAAN\AppData\Roaming\Python\Python36\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\ISHAAN\AppData\Roaming\Python\Python36\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """


In [29]:
testText = pd.read_csv('text_test_5_df.txt')
testAudio = pd.read_csv('audio_test_df.txt')
testVideo = pd.read_csv('visual_test_df.txt')
testAudio.bully[testAudio.bully == 'bullying'] = 1
testAudio.bully[testAudio.bully == 'noneBll'] = 0
# testVideo.bully[testVideo.bully == 'bullying'] = 1
# testVideo.bully[testVideo.bully == 'noneBll'] = 0

C:\Users\ISHAAN\AppData\Roaming\Python\Python36\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\ISHAAN\AppData\Roaming\Python\Python36\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """


In [30]:
x1train = trainAudio.iloc[:, 0:-2]
x2train = trainVideo.iloc[:, 0:-2]
x3train = trainText.iloc[:, 0:-2]
xtrain = pd.concat([x1train, x2train, x3train], axis=1)
ytrain = trainAudio.iloc[:, -1]
ytrain=ytrain.astype('int')

In [31]:
x1test = testAudio.iloc[:, 0:-2]
x2test = testVideo.iloc[:, :-2]
x3test = testText.iloc[:, :-2]
xtest = pd.concat([x1test, x2test, x3test], axis=1)
ytest = testAudio.iloc[:, -1]
ytest=ytest.astype('int')

In [32]:
sm = SMOTE(random_state=2)
x_train, y_train = sm.fit_sample(xtrain, ytrain.ravel())

In [48]:
from sklearn.svm import SVC
avSVM =SVC(kernel = 'linear', C = 10)
avSVM.fit(x_train, y_train)

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [49]:
ypredSVM = avSVM.predict(xtest)  
print(classification_report(ytest.values, ypredSVM))
print(confusion_matrix(ytest.values, ypredSVM)) 

             precision    recall  f1-score   support

          0       0.93      0.65      0.77       168
          1       0.43      0.85      0.57        52

avg / total       0.81      0.70      0.72       220

[[110  58]
 [  8  44]]


In [50]:
from sklearn.metrics import accuracy_score
print(accuracy_score(ytest,ypredSVM))

0.7


In [33]:
avGaussianNB = GaussianNB()
avGaussianNB.fit(x_train, y_train)

GaussianNB(priors=None)

In [34]:
from sklearn.metrics import accuracy_score
ypredNB = avGaussianNB.predict(xtest)
print(classification_report(ytest.values, ypredNB))
print(confusion_matrix(ytest.values, ypredNB)) 
print(accuracy_score(ytest,ypredNB))

             precision    recall  f1-score   support

          0       0.96      0.64      0.77       168
          1       0.44      0.92      0.60        52

avg / total       0.84      0.70      0.73       220

[[107  61]
 [  4  48]]
0.7045454545454546


In [35]:
avLR = LogisticRegression()
avLR.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [36]:
ypredLR = avLR.predict(xtest)
print(classification_report(ytest.values, ypredLR))
print(confusion_matrix(ytest.values, ypredLR))
print(accuracy_score(ytest,ypredLR))

             precision    recall  f1-score   support

          0       0.95      0.75      0.84       168
          1       0.52      0.88      0.66        52

avg / total       0.85      0.78      0.80       220

[[126  42]
 [  6  46]]
0.7818181818181819


In [37]:
avRF = RandomForestRegressor(n_estimators=20, random_state=0)
avRF.fit(x_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=20, n_jobs=1,
           oob_score=False, random_state=0, verbose=0, warm_start=False)

In [38]:
ypredRF = avRF.predict(xtest)
for x in range(len(ypredRF)):
    ypredRF[x] = 1 if ypredRF[x] >= 0.5 else 0

In [39]:
print(classification_report(ytest.values, ypredRF))
print(confusion_matrix(ytest.values, ypredRF))
print(accuracy_score(ytest,ypredRF))

             precision    recall  f1-score   support

          0       0.86      0.82      0.84       168
          1       0.48      0.56      0.52        52

avg / total       0.77      0.75      0.76       220

[[137  31]
 [ 23  29]]
0.7545454545454545


In [40]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 3)


In [41]:
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [44]:
knn_pred = knn.predict(xtest)

In [47]:
print(confusion_matrix(ytest.values, knn_pred))
print(classification_report(ytest,knn_pred))
print(accuracy_score(ytest,knn_pred))

[[110  58]
 [ 26  26]]
             precision    recall  f1-score   support

          0       0.81      0.65      0.72       168
          1       0.31      0.50      0.38        52

avg / total       0.69      0.62      0.64       220

0.6181818181818182
