In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn.metrics import classification_report, confusion_matrix  
from sklearn.naive_bayes import GaussianNB
from imblearn.over_sampling import SMOTE
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestRegressor

In [4]:
trainAudio = pd.read_csv('audio_train_df.txt')
trainVideo = pd.read_csv('visual_train_df.txt')
trainAudio.bully[trainAudio.bully == 'bullying'] = 1
trainAudio.bully[trainAudio.bully == 'noneBll'] = 0
trainVideo.bully[trainVideo.bully == 'bullying'] = 1
trainVideo.bully[trainVideo.bully == 'noneBll'] = 0

C:\Users\ISHAAN\AppData\Roaming\Python\Python36\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\ISHAAN\AppData\Roaming\Python\Python36\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\ISHAAN\AppData\Roaming\Python\Python36\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#i

In [6]:
testAudio = pd.read_csv('audio_test_df.txt')
testVideo = pd.read_csv('visual_test_df.txt')
testAudio.bully[testAudio.bully == 'bullying'] = 1
testAudio.bully[testAudio.bully == 'noneBll'] = 0
testVideo.bully[testVideo.bully == 'bullying'] = 1
testVideo.bully[testVideo.bully == 'noneBll'] = 0

C:\Users\ISHAAN\AppData\Roaming\Python\Python36\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\ISHAAN\AppData\Roaming\Python\Python36\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\ISHAAN\AppData\Roaming\Python\Python36\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#i

In [8]:
x1train = trainAudio.iloc[:, 0:-2]
x2train = trainVideo.iloc[:, 0:-2]
xtrain = pd.concat([x1train, x2train], axis=1)
ytrain = trainAudio.iloc[:, -1]
ytrain=ytrain.astype('int')

In [10]:
x1test = testAudio.iloc[:, 0:-2]
x2test = testVideo.iloc[:, :-2]
xtest = pd.concat([x1test, x2test], axis=1)
ytest = testAudio.iloc[:, -1]
ytest=ytest.astype('int')

In [11]:
sm = SMOTE(random_state=2)
x_train, y_train = sm.fit_sample(xtrain, ytrain.ravel())

In [12]:
avSVM = svm.SVC(kernel = 'linear', C = 10)
avSVM.fit(x_train, y_train)

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [13]:
ypredSVM = avSVM.predict(xtest)  
print(classification_report(ytest.values, ypredSVM))
print(confusion_matrix(ytest.values, ypredSVM)) 

             precision    recall  f1-score   support

          0       0.84      0.67      0.75       168
          1       0.36      0.60      0.45        52

avg / total       0.73      0.65      0.68       220

[[113  55]
 [ 21  31]]


In [14]:
from sklearn.metrics import accuracy_score
print(accuracy_score(ytest,ypredSVM))

0.6545454545454545


In [18]:
avGaussianNB = GaussianNB()
avGaussianNB.fit(x_train, y_train)

GaussianNB(priors=None)

In [21]:
ypredNB = avGaussianNB.predict(xtest)
print(classification_report(ytest.values, ypredNB))
print(confusion_matrix(ytest.values, ypredNB))
print(accuracy_score(ypredNB,ytest))

             precision    recall  f1-score   support

          0       0.84      0.51      0.63       168
          1       0.30      0.69      0.42        52

avg / total       0.71      0.55      0.58       220

[[85 83]
 [16 36]]
0.55


In [22]:
avLR = LogisticRegression(C = 10)
avLR.fit(x_train, y_train)

LogisticRegression(C=10, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [23]:
ypredLR = avLR.predict(xtest)
print(classification_report(ytest.values, ypredLR))
print(confusion_matrix(ytest.values, ypredLR))
print(accuracy_score(ypredLR,ytest))

             precision    recall  f1-score   support

          0       0.85      0.62      0.72       168
          1       0.35      0.65      0.45        52

avg / total       0.73      0.63      0.65       220

[[104  64]
 [ 18  34]]
0.6272727272727273


In [24]:
avRF = RandomForestRegressor(n_estimators=10, random_state=0)
avRF.fit(x_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=0, verbose=0, warm_start=False)

In [25]:
ypredRF = avRF.predict(xtest)
for x in range(len(ypredRF)):
    ypredRF[x] = 1 if ypredRF[x] >= 0.5 else 0
print(classification_report(ytest.values, ypredRF))
print(confusion_matrix(ytest.values, ypredRF))
print(accuracy_score(ypredRF,ytest))

             precision    recall  f1-score   support

          0       0.81      0.74      0.77       168
          1       0.33      0.42      0.37        52

avg / total       0.69      0.66      0.68       220

[[124  44]
 [ 30  22]]
0.6636363636363637


In [26]:
from sklearn.neighbors import KNeighborsClassifier

In [27]:
knn = KNeighborsClassifier(n_neighbors = 3)

In [28]:
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [29]:
knn_pred = knn.predict(xtest)

In [35]:
print(classification_report(ytest,knn_pred))
print(confusion_matrix(ytest,knn_pred))
print(accuracy_score(ytest,knn_pred))

             precision    recall  f1-score   support

          0       0.76      0.50      0.60       168
          1       0.24      0.50      0.32        52

avg / total       0.64      0.50      0.54       220

[[84 84]
 [26 26]]
0.5
